import 'package:videocalling/common/utils/app_imports.dart';

class Words extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      /// dialog
      'ok_btn': 'Ok',
      'error': 'Error!',
      'error2': 'Please try again',
      'error3': 'Something Wrong',
      'unable_to_save_token': 'Unable to save token to server',
      'turn_on_location_and_retry': 'Turn on location and retry',
      'creating_account': 'Creating Account',
      'creating_account1': 'Please wait while creating account...',
      'yes_btn': 'Yes',
      'no_btn': 'No',
      'cancel': 'Cancel',
      'btn_submit': 'Submit',
      'logout_title': 'Logout',
      'logout_description': 'Are you sure to logout',
      'logout_loading_title': 'Log out',
      'logout_loading_description': 'Please wait while log out...',
      'success': 'Successful',
      'success_str': 'Success',
      'payment_success': 'Your payment success',
      'not_logged_in': 'You are not logged in',
      'reporting_dialog1': 'Processing',
      'reporting_dialog2': 'Please wait while reporting issue...',
      'reporting_dialog3': 'No issue selected',
      'edit_dialog1': 'Updating details',
      'edit_dialog2': 'Please wait while updating details',
      'login_dialog_title': 'Logging In',
      'login_dialog_description': 'Please wait while logging in...',
      'fail': 'Fail',
      'fail_description': 'Your payment fail try again',
      'appointment_made_success': 'Appointment made successfully',
      'appoint_make_dialog': 'Please wait while making appointment',
      'while_saving_changes': 'Please wait while saving changes',
      'receipt_uploading': 'Receipt Uploading...',
      'upload_receipt_des1': 'Upload Recipe Description',
      'upload_receip': 'Upload Recipe',
      'remove_prescription': 'Remove Prescription',
      'upload_prescription': 'Upload Prescription',
      'prescription': 'Prescription',
      'continue_purchase': 'Continue To Purchase',
      'hello': 'Hello ',
      'choose_your_plan': 'CHOOSE YOUR PLAN',
      'choose_plan_t1': 'Monthly',
      'choose_plan_t2': 'Quarterly',
      'choose_plan_t3': 'HalfYear',
      'choose_plan_t4': 'Yearly',
      'd_subscription_plan_status1': 'Not Active',
      'd_subscription_plan_status2': 'Active',
      'd_subscription_plan_status3': 'Expire',
      'd_subscription_plan_status4': 'Reject',
      'month_str': 'Month',
      'save_str': 'Save 50%',
      'access_text': 'Access video calling',
      'available_text': '24/7 available',
      'choose_plan_des':
          'Doctor can purchase subscription and start using our app, after subscribe you can start dealing with your appointment, complete your profiles, set time slots, you can also check your reviews by users, and many more features',
      'call_dialog_title': 'Choose call type',
      'image_save_success': 'Image Save Successfully',
      'confirmation': 'Confirmation',
      'delete': 'Delete',
      'delete_report': 'Are you sure you want to delete this report?',
      'permission_not_granter': 'Permission not granted',
      'file_type_not_supported': 'File type not supported',
      'update_bank_details_dialog': 'Please wait while updating bank details',
      'update_bank_details_success': 'Bank detail update successful',
      'btn_complete': 'Complete',
      'btn_accept': 'Accept',
      'btn_cancel': 'Cancel',
      'btn_absent': 'Absent',
      'btn_upload': 'Upload',
      'profile_update_successfully': 'Profile updated successfully',

      /// tabs screen
      'home': 'Home',
      'appointment': 'Appointment',
      'doctor_login': 'Doctor login',
      'recent_chats': 'Recent chats',
      'more': 'More',
      'edit_profile': 'Edit profile',

      /// patient more screen
      'title1': 'Specialist',
      'title2': 'About',
      'title3': 'Term & Conditions',
      'title4': 'Report Issues',
      'title5': 'Logout',
      'sign_in_title': 'Sign In',
      'sign_in_title_1': 'Sign in to continue',
      'terms_and_conditions': 'Term & Conditions',
      'about': 'About us',
      'unable_to_load_data': 'Something went wrong, Unable to load data',
      'report_issue1': 'Doctor not taking appointments on time',
      'report_issue2': 'Doctor is spam and details are incorrect',
      'report_issue3': 'Address details are incorrect',
      'report_issue4': 'Doctors not treating well',
      'report_issue5':
          'Doctor accepted appointment but when i visit assistant diagnosing patients',
      'report': 'Report',
      'description_hint': 'Describe your issue',
      'description_error': 'Description is necessary',
      'enter_name': 'Enter Name',
      'enter_number': 'Enter mobile number',
      'enter_email_hint': 'Enter your email',
      'enter_email_error': 'Enter valid email address',
      'password_not_match': 'Password doesn\'t match',
      'confirm_password': 'Confirm Password',
      'password': 'Password',
      'update': 'Update',
      'next': 'Next',
      'speciality': 'Speciality',
      'doctor_not_found': 'Doctors Not Found',
      'appointment_fee': 'Appointment Fee',
      'not_specified': 'Not specified',
      'book_now': 'Book Now',
      'phone_number': 'Phone number',
      'doctor_detail': 'Doctor detail',
      'see_all_review': 'See all reviews',
      'review_str': 'reviews',
      'review': 'Review',
      'login_to_review': 'Login to add review',
      'no_review': 'No reviews',
      'add_a_review': 'Add a review',
      'your_rating': 'Your rating',
      'enter_message': 'Enter your message',
      'wait_for_while': 'Wait for a while...',
      'uploading_review': 'Uploading review',
      'login_to_book_appointment': 'Login to book appointment',
      'address': 'Address',
      'select_address_error': 'Select address from map',
      'working_time': 'Working time',
      'services': 'Services',
      'health_care_str': 'Heatlhcare',
      'health_care': 'Health care',
      'no_chats_title': 'No recent chats',
      'no_chats_description_user':
          '"To initiate chat with doctor you need to book appointment first”',
      'no_chats_description_doctor':
          '"You can initiate chat with user from appointment detail”',
      'all_appointment': 'All appointments',
      'past_appointment': 'Past Appointments',
      'not_appointment1': 'You don\'t have any appointment',
      'not_appointment2': 'Find best doctors near you by speciality,',
      'not_appointment3': 'click here',
      'either_mobile_number_is_incorrect':
          'Either email or password is incorrect',

      /// textfield error
      'valid_mobile_number': 'Enter valid mobile number',
      'description': 'Description',
      'common_textfield_error': 'This field is required',
      'please_select_image': 'Please select image',
      'enter_report_hint': 'Enter report name',
      'enter_report_error': 'Please enter report name',
      'search_medicine_error': 'Please enter medicine name',
      'search_medicine_hint': 'Search medicine',
      'add_new_medicine': 'Add as new medicine',
      'add_medicine': 'Add medicine',
      'name_label': 'Enter Medicine Name',
      'type_label': 'Enter Medicine Type',
      'type_error': 'Please Enter Medicine Type',
      'dosage_label': 'Enter Medicine Dosage',
      'dosage_error': 'Please Enter Medicine Dosage',
      'medicine_time_error': 'Please Enter medicine time',
      'about_us_error': 'Enter about us',
      'services_error': 'Enter services',
      'working_error': 'Enter working time',
      'select_department_hint': 'Select department',
      'name_hint': 'Name',

      /// register text
      'already_have_an_account': 'Already have an account?',
      'not_have_an_account': 'Don\'t have account?',
      'register': 'Register',
      'doctor_register': 'Register as doctor',
      'register_now': ' Register Now',
      'forget_password': 'Forget Password ?',
      'login_now': 'Login Now',
      'login': 'Login',
      'remove': 'Remove',
      'enter_6_characters': 'Please Enter atleast 6 characters',
      'either_email_password_incorrect':
          'Either email or password is incorrect',
      'mobile_error_1': 'Please Enter mobile Number',
      'mobile_error_2': 'Please Enter atleast @length digits',
      'password_error': 'Password doesn\'t match',
      'password_error1': 'Please Enter Confirm Password',
      'password_error2': 'Please Enter atleast @length characters',
      'forget_password_enter_email':
          'Enter the email address associated with your account',
      'we_will_email_a_password_reset_link':
          'We will email you a link to reset you password',
      'please_wait_while_processing': 'Please wait while processing...',
      'loading': 'Loading...',
      'welcome_str': 'Welcome ',
      'user_str': 'User',
      'continue_with_google': 'Continue with google',
      'month1': 'Jan',
      'month2': 'Feb',
      'month3': 'March',
      'month4': 'April',
      'month5': 'May',
      'month6': 'June',
      'month7': 'July',
      'month8': 'Aug',
      'month9': 'Sep',
      'month10': 'Oct',
      'month11': 'Nov',
      'month12': 'Dec',
      'month_full_1': 'January',
      'month_full_2': 'February',
      'month_full_3': 'March',
      'month_full_4': 'April',
      'month_full_5': 'May',
      'month_full_6': 'June',
      'month_full_7': 'July',
      'month_full_8': 'August',
      'month_full_9': 'September',
      'month_full_10': 'October',
      'month_full_11': 'November',
      'month_full_12': 'December',
      'day1': 'Sun',
      'day2': 'Mon',
      'day3': 'Tue',
      'day4': 'Wed',
      'day5': 'Thu',
      'day6': 'Fri',
      'day7': 'Sat',
      'day_full_1': 'Monday',
      'day_full_2': 'Tuesday',
      'day_full_3': 'Wednesday',
      'day_full_4': 'Thursday',
      'day_full_5': 'Friday',
      'day_full_6': 'Saturday',
      'day_full_7': 'Sunday',
      'day_text_1': '1 Day',
      'day_text_2': '2 Days',
      'day_text_3': '3 Days',
      'day_text_4': '4 Days',
      'day_text_5': '5 Days',
      'day_text_6': '6 Days',
      'day_text_7': '7 Days',
      'day_text_8': '8 Days',
      'day_text_9': '9 Days',
      'day_text_10': '10 Days',
      'doc_on_leave_title': 'Doctor on leave',
      'doc_on_leave_description':
          'Not possible to book appointment on @date as doctor in on leave',
      'make_an_appointment': 'Make an appointment',
      'process_payment': 'Process Payment',
      'consultation_fee': 'Consultation fee',
      'select_a_payment_method': 'Select payment method',
      'method1_title': 'Cash On Board',
      'method1_description':
          'Pay only on visiting doctor at your appointment time',
      'method2_title': 'Paystack',
      'method3_title': 'Rave',
      'method4_title': 'Paytm',
      'method5_title': 'Braintree',
      'method5_description':
          'use your credit/debit card or PayPal account to pay consultation fee',
      'method6_title': 'Stripe',
      'method6_description':
          'use your credit/debit card to pay consultation fee',
      'method7_title': 'Razorpay',
      'common_description': 'use your credit/debit card to pay appointment fee',
      'no_slot_available': 'No slot available',
      'past_time_slots': 'You can\'t select past time slots',
      'select_appointment_time': 'Please select appointment time',
      'upload_receipt': 'Upload Receipt',
      'upload_receipt_des': 'Upload Payment Receipt',
      'make_an_subscribe': 'Make an subscribe',

      /// appointment details
      'user_no_prescription_msg':
          'You do not have any prescription yet, Doctor will add after consultation.',
      'user_no_prescription_msg1': 'Here is your prescription.',
      'user_no_report_msg':
          'You do not have any Reports yet, Doctor will suggest if required after consultation.',
      'user_no_report_msg1': 'Here is your report.',
      'appointment_status_1': 'Absent',
      'appointment_status_2': 'Received',
      'appointment_status_3': 'Approved',
      'appointment_status_4': 'In Process',
      'appointment_status_5': 'Completed',
      'appointment_status_6': 'Rejected',
      'email_address': 'Email Address',
      'consume_it_days': 'Consume it for @days Days',
      'download_prescription': 'Download prescription',
      'medicine_param1': 'Type',
      'medicine_param2': 'Dosage',
      'medicine_param3': 'Time',
      'medicine_param4': 'Edit',
      'nearby_doctors': 'Nearby Doctors',
      'search_doctor_appbar1': 'search, ',
      'search_doctor_appbar2': 'Here',
      'search_doctor_name': 'Search doctor by name',
      'change_password_str': 'Change Password',
      'old_pwd': 'Old Password',
      'new_pwd': 'New Password',
      'old_pwd_error': 'Please Enter Old Password',
      'new_pwd_error': 'Please Enter New Password',
      'conf_pwd_error': 'Please Enter Confirm Password',
      'subscription_list': 'Subscription List',
      'subscription_str': 'Subscription',
      'income_report_tile_text1': 'Today\'s Earning Report',
      'income_report_tile_text2': 'Last 7 Days Earning Report',
      'income_report_tile_text3': 'Last 30 Days Earning Report',
      'income_report_tile_short_text1': 'Today\'s',
      'income_report_tile_short_text2': 'Last 7 day\'s',
      'income_report_tile_short_text3': 'Last 30 day\'s',
      'income_report_tile_text4': 'Select Date Range',
      'income_report_str': 'Income Report',
      'detailed_report': 'Detailed Reports',
      'total_income_str': '@option total income',
      'filter_report_by': 'Filter Reports by',
      'not_any_income_str': '@option you have not any income.',

      /// chat screen
      'media_upload_title': 'Choose type',
      'send_text_field_hint': 'Type a message here...',
      'first_conversation_title': 'You didn\'t made any conversation yet',
      'first_conversation_title1': 'Say Hi',
      'first_conversation_title2': 'No Conversations',
      'seen_str': 'seen ',
      'send_file': 'Sending File',
      'uploading_file': 'Uploading File',
      'uploading_file1': 'Uploading file...',
      'chat_title_today': 'Today',
      'chat_title_yesterday': 'Yesterday',
      'accept_chat_dialog_text1': 'Reject',
      'accept_chat_dialog_text2': 'Accept',
      'photo_str': 'Photo',
      'video_str': 'Video',
      'chat_time_yesterday': 'yesterday',
      'chat_time_day_ago': '@day days ago',
      'remove_msg_title': 'Remove Message',
      'remove_msg_subtitle': 'Are you sure to remove this message ?',

      'bank_details': 'Bank details',
      'update_bank_details': 'Update bank details',
      'bank_name': 'Payment provider',
      'bank_name_error': 'Enter payment provider',
      'account_name': 'Account holder / display name',
      'account_name_error': 'Enter account holder name',
      'account_number': 'Reference account number',
      'account_number_error': 'Enter reference account number',
      'conf_account_number': 'Confirm reference account number',
      'conf_account_number_error': 'Confirm reference account number',
      'more_info': 'More Info',
      'no_address': 'Address goes here...',
      'choose_gallery': 'Choose from gallery',
      'doctor_not_appointment_text': 'You don\'t have any appointment',
      'd_add_prescription_msg': 'Write prscription for the patient.',
      'd_add_report_msg': 'Add reports of patient',
      'add_prescription': 'Add Prescription',
      'medicine_param_1': 'Type :',
      'medicine_param_2': 'Dosage :',
      'medicine_param_3': 'Consuming Time :',
      'medicine_param_4': 'Consuming is for :',
      'medicine_param_5': 'Consume it for :',
      'add_reports': 'Add Reports',
      'upload_report': 'Upload Report',
      'complete_appointment_subtitle':
          'Are you sure you want to complete this appointment?',
      'delete_medicine': 'Are you sure you want to delete this medicine?',
      'medicine_str': 'Medicine',
      'edit_data_btn': 'Edit Data',
      'add_to_prescription_btn': 'Add To Prescription',
      'call_accept_dialog_title': 'Call Accepting',
      'call_accept_dialog_subtitle': 'Please wait your call is accepting...',
      'doctor_dashboard': 'Doctor dashboard',
      'appointments_str': 'Appointments',
      'see_all': 'see all',
      'pdf_downloading': 'Pdf Downloading...',
      'downloading_done': 'Downloading Done !',
      'pdf_downloader': 'Pdf Downloader',
      'upcoming_appointments': 'Upcoming Appointments',
      'min_str': 'Min',
      'profile_str': 'Profile',
      'start_time': 'Start time',
      'end_time': 'End time',
      'save': 'Save',
      'am_str': ' AM',
      'pm_str': ' PM',
      'empty_str': 'Empty',
      'no_changes_made': 'No changes have been made',
      'end_time_small_then_start_time':
          'Ending time can\'t be smaller than starting time',
      'timing_wrong': 'Timings entered incorrectly',
      'select_interval': 'Select interval',
      'start_end_time_wrong': 'Start/End time not entered correctly',
      'time_slot_added_successfully': 'Time Slot Added Successfully',
      'no_holiday_title': 'No holidays so far',
      'no_holiday_subtitle': 'Your holiday list will appear here',
      'add_holiday': 'Add Holiday',
      'update_holiday': 'Update Holiday',
      'select_date': 'Select Date',
      'select_date_desc':
          'Select a date or a number of dates for adding then to your holidays list',
      'add_date_error': 'Please select a date to add it in your holiday list',
      'days_holiday': ' Days Holiday',
      'data_not_found': 'Data Not found!',
      'specialist': ' specialist',
      'ringing': 'Ringing',
      'audio_call': 'Audio call',
      'members': 'Members:',
      'permission_not_granted': 'Permission not granted',
      'permission_not':
          'We required location permission to server you nearby doctors.',
      'call_accept_subtitle':
          'For accepting the calls in the background you should provide access to show System Alerts from the background. Would you like to do it now?',
      'call_accept_title': 'Permission required',
      "preparing_call": "Preparing call...",
      "call_service_not_ready":
          "Call service is not ready. Please try again in a moment.",
      "exit": "Exit",
      "exit_confirmation": "Are you sure you want to exit?",
      "no": "No",
      "yes": "Yes",
      'cannot_start_call': 'Cannot Start Call',
      'appointment_not_accepted_for_call':
          'You haven\'t accepted this appointment yet, you can\'t start call for this appointment',
      'appointment_cancelled': 'Appointment Cancelled',
      'appointment_cancelled_chat_message':
          'This appointment has been cancelled, you can\'t send messages in this chat',
      'appointment_rejected': 'Appointment Rejected',
      'appointment_rejected_chat_message':
          'This appointment has been rejected, you can\'t send messages in this chat',
      'appointment_completed': 'Appointment Completed',
      'appointment_completed_chat_message':
          'This appointment has been completed, you can\'t send messages in this chat',
      'appointment_not_accepted': 'Appointment Not Accepted',
      'wait_for_doctor_acceptance': 'Please wait for doctor acceptance',
      "verify_email_title": "Verify Your Email",
      "verify_email_message":
          "A verification link has been sent to {{email}}. Please check your inbox and verify your email before logging in.",
      "email_not_verified": "Email Not Verified",
      "verification_email_sent_to":
          "A verification email has been sent to {{email}}",
      "check_inbox_and_spam": "Please check your inbox and spam folder.",
      "resend_email": "Resend Email",
      "verification_email_resent":
          "Verification email has been resent successfully.",
      "sending": "Sending...",
      "please_wait": "Please wait",
      "unable_to_send_email": "Unable to send email. Please try again.",
      "license_number": "License Number",
      "license_number_required": "License number is required",
      "upload_certificate": "Upload Certificate",
      "certificate_required": "Certificate is required",
      "registration_successful": "Registration Successful",
      "account_under_review": "Account Under Review",
      "cannot_start_chat": "Cannot Start Chat",
      "appointment_not_accepted_for_chat":
          'You haven\'t accepted this appointment yet, you can\'t start chat for this appointment',
    },
    'de_DE': {'hello': 'Hallo Welt'},
  };
}
