name: iOS IPA Build

on:
  workflow_dispatch: # allows manual trigger

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.9' # or your Flutter stable version

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Pre-build for iOS
        run: |
          flutter clean
          flutter precache --ios

      - name: Build IPA
        env:
          FLUTTER_BUILD_NAME: 1.0.0
          FLUTTER_BUILD_NUMBER: 1
        run: |
          flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
